// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMzvqRj3B8jwOSOGirAsRSNNz6oS2FpVw',
    appId: '1:11030148304:web:75ef0fef79b8dba1701ad5',
    messagingSenderId: '11030148304',
    projectId: 'mygarage-8550b',
    authDomain: 'mygarage-8550b.firebaseapp.com',
    storageBucket: 'mygarage-8550b.appspot.com',
    measurementId: 'G-M1YCZP2XCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc2n1Rc5dxT9QpIKqRjC98GHFhAQ4ZCFc',
    appId: '1:11030148304:android:7cbcd06535f97ece701ad5',
    messagingSenderId: '11030148304',
    projectId: 'mygarage-8550b',
    storageBucket: 'mygarage-8550b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUFiQBxo6YqrZsjbq7DRAoqjKsmz1lK-Y',
    appId: '1:11030148304:ios:e376d0ce228f7c24701ad5',
    messagingSenderId: '11030148304',
    projectId: 'mygarage-8550b',
    storageBucket: 'mygarage-8550b.appspot.com',
    iosBundleId: 'com.example.myGarage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUFiQBxo6YqrZsjbq7DRAoqjKsmz1lK-Y',
    appId: '1:11030148304:ios:5942b805689b51b6701ad5',
    messagingSenderId: '11030148304',
    projectId: 'mygarage-8550b',
    storageBucket: 'mygarage-8550b.appspot.com',
    iosBundleId: 'com.example.myGarage.RunnerTests',
  );
}
